

-- GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

-- CHANGE MASTER TO MASTER_HOST='localhost', MASTER_USER='user', MASTER_PASSWORD='1234', GET_MASTER_PUBLIC_KEY=1, MASTER_LOG_FILE='mysql-bin.000003', MASTER_LOG_POS=15385;

-- START SLAVE;

CREATE DATABASE meetup_study_DB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
