
CREATE DATABASE meetup_study_DB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;
GRANT REPLICATION SLAVE ON *.* TO 'user'@'%';

FLUSH PRIVILEGES;

STOP SLAVE;